services:
  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
      # test ports
      - "8080:8080"
      - "8443:8443"
      - "8443:8443/udp"
    extra_hosts:
      - "host-docker-internal:host-gateway"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./certs:/srv/certs
      - caddy-data-vol:/data
      - caddy-config-vol:/config

  backup:
    extends:
      file: ../dvb/docker-compose.yml
      service: backup
    environment:
      - BACKUP_PREFIX=caddy
    volumes:
      - caddy-data-vol:/backup/caddy-data-vol-backup:ro
      - caddy-config-vol:/backup/caddy-config-vol-backup:ro

volumes:
  caddy-data-vol:
  caddy-config-vol:

