services:
  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
      # test ports
      - "8080:8080"
      - "8443:8443"
      - "8443:8443/udp"
    extra_hosts:
      - "host-docker-internal:host-gateway"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./certs:/srv/certs
      - caddy-data-vol:/data
      - caddy-config-vol:/config

volumes:
  caddy-data-vol:
  caddy-config-vol:

