services:
  api:
    container_name: !reset
    ports: !override
      - '9080:3080'
    volumes:
      - ./librechat.yaml:/app/librechat.yaml
      - ./volumes/images:/app/client/public/images
      - ./volumes/uploads:/app/uploads
      - ./volumes/logs:/app/api/logs
    
  mongodb:
    container_name: !reset
    user: !reset
    volumes:
      - mongodb-vol:/data/db

  meilisearch:
    container_name: !reset
    user: !reset
    volumes:
      - meili-data-vol:/meili_data

  vectordb:
    container_name: !reset

  rag_api:
    container_name: !reset

volumes:
  mongodb-vol:
  meili-data-vol:

