services:
  commafeed:
    image: athou/commafeed:latest-h2
    restart: unless-stopped
    volumes:
      - ./vols/data:/commafeed/data
    deploy:
      resources:
        limits:
          memory: 1G
    ports:
      - 9082:8082

